name: build
on: [push, pull_request]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.16

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Test
              run: |
                  go mod init github.com/Purgas/wordcount
                  go build .
                  ./wordcount '' | grep -E "^0$"
                  ./wordcount 'ok' | grep -E "^1$"
                  ./wordcount 'go is awesome' | grep -E "^3$"
                  ./wordcount 'php - not so much' | grep -E "^5$"
